### PR TITLE
update relationship for GlobSed and latest agegrid

### PR DESCRIPTION
**Pull request by nickywright**
Update sediment thickness/rate relationship for GlobSed and most recent age grid.

### CODE REVIEW

**Comment by michaelchin** [comment]
@nickywright I saw you closed this PR but did not merge the code. Just out of curiosity, did you have "write permission" problem? I saw your role in this repository had a "mixed role" warning. Just checking to see if it was causing problems.

**Comment by nickywright** [comment]
sorry @michaelchin! I closed it because I ended up making more changes in my fork (changed some path names, added comments, and will change to the gplates sample data shortly) and I couldn’t figure out how to modify the pull request with this to do it in one! Never done a pull request before so thought that would be easier (though I could just do two PRs if needed)

**Comment by michaelchin** [comment]
> sorry @michaelchin! I closed it because I ended up making more changes in my fork (changed some path names, added comments, and will change to the gplates sample data shortly) and I couldn’t figure out how to modify the pull request with this to do it in one! Never done a pull request before so thought that would be easier (though I could just do two PRs if needed)

You can continue to make changes and commits to a PR before it is merged. The new commits will show up in the PR automatically.

**Comment by michaelchin** [comment]
If you like, you can reopen this PR and try it.

**Comment by michaelchin** [comment]
And you might want to fix the "mixed roles" warning. It is in Settings->Collaborators and Teams.

**Pull request merged**
